version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-
      - run: yarn global add node-gyp && yarn install
      - run:
                    name: Install local dependencies
                    command: npm install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}

  install:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-
 
      - run: yarn build
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}

  server-doc-build:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
      - run: yarn build
      - run:
          name: Copy deployment artifacts to workspace
          command: |
            cp server-dist/ /tmp/server-dist -r
      - store_artifacts:
          path: /tmp/server-dist
      - persist_to_workspace:
          root: /tmp
          paths:
            - server-dist

  deploy-netlify:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/deploy-dist-server
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Deploy app
          command: |
            npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --dir /tmp/server-dist --prod

workflows:
  version: 2
  build-test-and-lint2:
    jobs:
      - build
      - install:
          requires:
            - build
      - server-doc-build:
          requires:
            - install
            - build
          filters:
            branches:
              only: main
      - deploy-netlify:
          requires:
            - server-doc-build
          filters:
            branches:
              only: main
